name: Build and Package Multiarch GCC

on:
  workflow_dispatch:
    inputs:
      gcc_version:
        description: 'GCC version to build'
        required: true
        default: '10.5.0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/i386, linux/arm64, linux/arm/v7]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Container
        run: docker run --rm --platform ${{ matrix.platform }} -v ${{ github.workspace }}:/workspace ubuntu:16.04 /bin/bash /workspace/build.sh ${{ github.event.inputs.gcc_version }}

      - name: Upload GCC Package (tar & deb)
        uses: actions/upload-artifact@v4
        with:
          name: gcc-${{ github.event.inputs.gcc_version }}-${{ matrix.platform }}
          path: |
            gcc-${{ github.event.inputs.gcc_version }}-*.tar.*
            gcc-${{ github.event.inputs.gcc_version }}-*.deb

